name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # 確認這是最新版並支持 Node.js 20

      - name: Set up Node.js
        uses: actions/setup-node@v3  # 確認這是最新版並支持 Node.js 20
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4  # 使用適當的版本
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
